#!/usr/bin/env python3

import os
import re
import textwrap

def undent(s):
  return re.sub('\n +','\n',s.lstrip())

def config(subject, sans):
    names = list(enumerate(sans, 1))
    dns = [f"DNS.{i} = {n}" for i,n in names if re.match("^\D", n)]
    ips = [f"IP.{i} = {n}" for i,n in names if re.match("^\d", n)]
    names = "\n".join(dns + ips)
    text = undent(f"""
        [req]
        distinguished_name = dn
        req_extensions = v3_req
        default_bits = 2048
        prompt = no
        default_md = sha256
        [dn]
        C = UK
        ST = England
        L = London
        O = example.com
        emailAddress = hostmaster@example.com
        CN = {subject}
        [v3_req]
        keyUsage = keyEncipherment, dataEncipherment
        extendedKeyUsage = serverAuth
        subjectAltName = @alt_names
        [alt_names]
        {names}
        """)
    with open(f"{subject}.cnf", 'w') as f:
      f.write(text)

def key(subject):
    os.system(f"openssl genrsa -out {subject}.key 4096")

def csr(subject, sans):
    config(subject, sans)
    os.system(f"openssl req -new -nodes -sha256 -key {subject}.key -config {subject}.cnf -out {subject}.csr")

def sign(subject):
    os.system(f"openssl x509 -req -in {subject}.csr -extfile {subject}.cnf -extensions v3_req -out {subject}.crt -CA cacert.pem -CAkey private/cakey.key -CAcreateserial -days 3650 -sha256")

key("www.foo.com")
csr("www.foo.com", ["foo.com", "home.foo.com", "10.0.0.1", "10.0.0.2"])
sign("www.foo.com")
